from flask import Flask, request, flash, redirect, url_for, render_template
from models import *

app = Flask(__name__)


# This hook ensures that a connection is opened to handle any queries
# generated by the request.
@app.before_request
def _db_connect():
    db.connect()

# This hook ensures that the connection is closed when we've finished
# processing the request.
@app.teardown_request
def _db_close(exc):
    if not db.is_closed():
        db.close()

@app.route('/')
def index():
    return 'Job is done! Check your database!'

# Displaying registration form
@app.route('/registration', methods=['GET', 'POST'])
def reg_confirmation():
    if request.method == "POST":
        Applicant.create(first_name=request.form['fname'], last_name=request.form['lname'], location=request.form['location'],
                         email=request.form['email'])
        return redirect('/')
    else:
        return render_template('regform.html')

if __name__ == '__main__':
    app.run()